apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mobius-server-dev-pv-claim-11.2.6-efs
  namespace: mobius-dev
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-server-11.2.6-efs
