apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mobiusview-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - pods 
  - nodes
  verbs:
  - get
  - list
