apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mobiusview-cluster-role-binding
  namespace: mobius-ct
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mobiusview-cluster-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: mobius-ct

