apiVersion: v1
kind: PersistentVolume
metadata:
  name: ifw-volume
  labels:
    type: ifw-volume 
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  
  hostPath:
    path: "/home/rocket/ifw-volume"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ifw-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector: 
    matchLabels: 
      type: ifw-volume      
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ifw-inbox
  labels:
    type: ifw-inbox 
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  
  hostPath:
    path: "/home/rocket/ifw-inbox"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ifw-inbox-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector: 
    matchLabels: 
      type: ifw-inbox     