apiVersion: batch/v1
kind: Job
metadata:
  name: install-mobius-remote-cli-sleep
spec:
  template:
    spec:
     containers:
      - name: install-mobius-remote-cli-sleep
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - sleep 999999999999
        volumeMounts:
        - mountPath: "/inbox"
          name: "ifw-inbox-claim" 
        - mountPath: "/volume"
          name: "ifw-volume-claim"                     
     restartPolicy: Never
     volumes:
     - name: "ifw-inbox-claim"
       persistentVolumeClaim:
         claimName: "ifw-inbox-claim"  
     - name: "ifw-volume-claim"
       persistentVolumeClaim:
         claimName: "ifw-volume-claim"                  
  backoffLimit: 4