apiVersion: batch/v1
kind: Job
metadata:
  name: install-mobius-remote-cli
spec:
  template:
    spec:
     containers:
      - name: install-mobius-remote-cli
        image: byrnedo/alpine-curl
        command: ["/bin/sh", "-c"]
        args:
        - curl -k -o /inbox/MobiusRemoteCLI.tar https://myshare.rocketsoftware.com/myshare/d/PqgkLvj51 && curl -k -o /inbox/setup.sh https://raw.githubusercontent.com/Guillermo-Avendano/k3d-rock/main/inputframework/MobiusRemoteCLI/setup.sh && chmod +x /inbox/setup.sh && . /inbox/setup.sh
        volumeMounts:
        - mountPath: "/inbox"
          name: "ifw-inbox-claim" 
        - mountPath: "/volume"
          name: "ifw-volume-claim"                     
     restartPolicy: Never
     volumes:
     - name: "ifw-inbox-claim"
       persistentVolumeClaim:
         claimName: "ifw-inbox-claim"  
     - name: "ifw-volume-claim"
       persistentVolumeClaim:
         claimName: "ifw-volume-claim"                  
  backoffLimit: 4