FROM registry.rocketsoftware.com/mobius-server:12.2.0

USER mobius

COPY libLPFDUtil.so /opt/asg/vdrnet12.2/vdrsoa/webapps/vdrerp/WEB-INF/lib/libLPFDUtil.so
COPY libLPFDUtil.so /opt/asg/vdrnet12.2/lib/libLPFDUtil.so
