version: "3"
volumes:
  cups_data:
services:
    cups:
        image: anujdatar/cups
        container_name: cups
        ports:
          - "631:631"
        devices:
          - /dev/bus/usb:/dev/bus/usb
        environment:
            - CUPSADMIN=batman
            - CUPSPASSWORD=batcave_password
            - TZ="America/Gotham"
        volumes:
          - cups_data:/etc/cups