version: "3.0"

services: 
  outbound:
    image: guillermoavendano/outbound:6.1.1
    command: ["/bin/sh", "-c", "chmod -R 777 /data ; /opt/obent/startup.sh 2>&1"]
    ports:
      - '1803:19803'
    container_name: outbound6.1.1
    volumes:
    - ./ftp:/data
