apiVersion: v1
kind: PersistentVolume
metadata:
  name: mobius-storage
  labels:
    type: mobius-storage
spec:
  storageClassName: <KUBE_STORAGE_CLASS>
  capacity:
    storage: 1Gi
  accessModes:
    - <KUBE_STORAGE_READ_WRITE>
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mobius-storage-claim
spec:
  storageClassName: <KUBE_STORAGE_CLASS>
  accessModes:
    - <KUBE_STORAGE_READ_WRITE>
  resources:
    requests:
      storage: 1000M
  selector: 
    matchLabels: 
      type: mobius-storage    
---      
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mobius-diagnose
  labels:
    type: mobius-diagnose
spec:
  storageClassName: <KUBE_STORAGE_CLASS>
  capacity:
    storage: 1Gi
  accessModes:
    - <KUBE_STORAGE_READ_WRITE>
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mobius-diagnose-claim
spec:
  storageClassName: <KUBE_STORAGE_CLASS>
  accessModes:
    - <KUBE_STORAGE_READ_WRITE>
  resources:
    requests:
      storage: 1000M
  selector: 
    matchLabels: 
      type: mobius-diagnose   
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mobius-fts-pv-claim
spec:
  storageClassName: <KUBE_STORAGE_CLASS>
  accessModes:
    - <KUBE_STORAGE_READ_WRITE>
  resources:
    requests:
      storage: 1000M