apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mobius-storage-claim
spec:
  storageClassName: <KUBE_STORAGE_CLASS>
  accessModes:
    - <KUBE_STORAGE_READ_WRITE>
  resources:
    requests:
      storage: 1000M   
---      
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mobius-diagnose-claim
spec:
  storageClassName: <KUBE_STORAGE_CLASS>
  accessModes:
    - <KUBE_STORAGE_READ_WRITE>
  resources:
    requests:
      storage: 1000M  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mobius-fts-pv-claim
spec:
  storageClassName: <KUBE_STORAGE_CLASS>
  accessModes:
    - <KUBE_STORAGE_READ_WRITE>
  resources:
    requests:
      storage: 1000M