apiVersion: v1
kind: PersistentVolume
metadata:
  name: mobius-storage
  labels:
    type: mobius-storage
spec:
  storageClassName: <KUBE_STORAGE_CLASS>
  capacity:
    storage: 10Gi
  accessModes:
    - <KUBE_STORAGE_READ_WRITE>
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "<MOBIUS_PV_STORAGE>"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mobius-storage-claim
spec:
  storageClassName: <KUBE_STORAGE_CLASS>
  accessModes:
    - <KUBE_STORAGE_READ_WRITE>
  resources:
    requests:
      storage: 10Gi
  selector: 
    matchLabels: 
      type: mobius-storage    
---      
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mobius-diagnose
  labels:
    type: mobius-diagnose
spec:
  storageClassName: <KUBE_STORAGE_CLASS>
  capacity:
    storage: 2Gi
  accessModes:
    - <KUBE_STORAGE_READ_WRITE>
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "<MOBIUS_PV_DIAGNOSE>"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mobius-diagnose-claim
spec:
  storageClassName: <KUBE_STORAGE_CLASS>
  accessModes:
    - <KUBE_STORAGE_READ_WRITE>
  resources:
    requests:
      storage: 2Gi
  selector: 
    matchLabels: 
      type: mobius-diagnose   
