apiVersion: v1
kind: Service
metadata:
  name: printagent  
  namespace: mobius
  annotations:
    service.kubernetes.io/topology-mode: auto
spec:
  ports:
    - port: 7070
      name: printagent
      protocol: TCP
      targetPort: 7070
#-----------------------------------------
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: mobius-printagent
  namespace: mobius
  labels:
    kubernetes.io/service-name: printagent
addressType: IPv4
ports:
  - name: printagent
    protocol: TCP
    port: 7070
endpoints:
  - addresses:
      - "10.0.0.4"
    conditions:
      ready: true