apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-2g-pv

spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi

  nfs:
    path: /var/nfs/general
    server: 10.0.0.2