apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pv-claim-aas
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  