apiVersion: v1
data:
  application.yaml: |
    asg:
      mobius:
        cli:
          repos:
          - repositoryName: "Mobius"
            repositoryUrl: "http://{{ .Values.mobiusRemoteCLI.hostPort }}/mobius"
            userName: "ADMIN"
          user:
            basicauth:
              userName: "admin"
              password: "ASG_ENC(i9motYxCmo6RLqOiHifcDw==)"
kind: ConfigMap
metadata:
  name: application-yaml-config-map

