apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    inputframework: web
  ports:
  - name: inputframework
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}  
---
kind: Service 
apiVersion: v1 
metadata:
  name: {{ .Values.service.name }}-nodeport-30779
spec:
  type: NodePort
  selector:
    inputframework: web
  ports:
    # Three types of ports for a service
    # nodePort - a static port assigned on each the node
    # port - port exposed internally in the cluster
    # targetPort - the container port to send requests to
    - nodePort: 30779
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}  
    


