apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    inputframework: web
  ports:
  - name: inputframework
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}  
    


