apiVersion: v1
kind: PersistentVolume
metadata:
  name: mobiusview-presentation
  labels:
    type: mobiusview-presentation
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "<MOBIUSVIEW_PV_PRESENTATION>"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mobiusview-presentation-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000M
  selector: 
    matchLabels: 
      type: mobiusview-presentation    
---      
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mobiusview-diagnose
  labels:
    type: mobiusview-diagnose
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "<MOBIUSVIEW_PV_DIAGNOSE>"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mobiusview-diagnose-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000M
  selector: 
    matchLabels: 
      type: mobiusview-diagnose    
 