apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mobiusview-presentation-claim
spec:
  storageClassName: <KUBE_STORAGE_CLASS>
  accessModes:
    - <KUBE_STORAGE_READ_WRITE>
  resources:
    requests:
      storage: 1000M   
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mobiusview-diagnose-claim
spec:
  storageClassName: <KUBE_STORAGE_CLASS>
  accessModes:
    - <KUBE_STORAGE_READ_WRITE>
  resources:
    requests:
      storage: 1000M 
 