apiVersion: v1
kind: PersistentVolume
metadata:
  name: aas-log-vol
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "<AAS_PV_LOG>"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <AAS_PVC_LOG>
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aas-shared
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "<AAS_PV_SHARED>"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <AAS_PVC_SHARED>
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi