apiVersion: v1
kind: PersistentVolume
metadata:
  name: aas-log-vol
spec:
  storageClassName: <KUBE_STORAGE_CLASS>
  capacity:
    storage: 1Gi
  accessModes:
    - <KUBE_STORAGE_READ_WRITE>
  hostPath:
    path: "<AAS_PV_LOG>"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <AAS_PVC_LOG>
spec:
  storageClassName: <KUBE_STORAGE_CLASS>
  accessModes:
    - <KUBE_STORAGE_READ_WRITE>
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aas-shared
spec:
  storageClassName: <KUBE_STORAGE_CLASS>
  capacity:
    storage: 1Gi
  accessModes:
    - <KUBE_STORAGE_READ_WRITE>
  hostPath:
    path: "<AAS_PV_SHARED>"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <AAS_PVC_SHARED>
spec:
  storageClassName: <KUBE_STORAGE_CLASS>
  accessModes:
    - <KUBE_STORAGE_READ_WRITE>
  resources:
    requests:
      storage: 1Gi