apiVersion: v1
data:
  application.yaml: |
    asg:
      mobius:
        cli:
          repos:
          - repositoryName: "Mobius"
            repositoryUrl: "http://mobiusview:80/mobius"
            userName: "ADMIN"
          user:
            basicauth:
              userName: "admin"
              password: "ASG_ENC(OA5gY2gyVDx1QYQsyd6Mmw==)"

kind: ConfigMap
metadata:
  name: application-yaml-config-map

