apiVersion: batch/v1
kind: Job
metadata:
  name: job-mobius-demo-12-2-1-all
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: job-mobius-demo-12-2-1-all
        image: "guillermoavendano/mobiusdatasampler:12.2.1"
        command: ["/bin/bash", "-ec", "./all.sh"]
        env:
          - name: MV_USR
            value: "2002"
          - name: MV_GRP
            value: "0"
        volumeMounts:
          - mountPath: /mnt/efs
            name:  mobius-content-classes
          - mountPath: /root/asg/mobius/mobius-cli/
            name: application-yaml-config-map
          - mountPath: /root/asg/security/
            name: secret-sec-config-map              
      volumes:
        - name: mobius-content-classes
          persistentVolumeClaim: 
            claimName: "mobius-storage-claim"              
        - name: "application-yaml-config-map" 
          configMap:
            name: "application-yaml-config-map"
        - name: "secret-sec-config-map"
          configMap:
            name: "secret-sec-config-map"   