apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: if-volume-claim
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000M   
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: if-input-claim
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000M   