apiVersion: v1
kind: PersistentVolume
metadata:
  name: ifw-volume
  labels:
    type: ifw-volume 
spec:
  storageClassName: <KUBE_STORAGE_CLASS>
  capacity:
    storage: 1Gi
  accessModes:
    - <KUBE_STORAGE_READ_WRITE>
  persistentVolumeReclaimPolicy: Retain  
  hostPath:
    path: "<IFW_PV_VOLUME>"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <IFW_PVC_VOLUME>
spec:
  storageClassName: <KUBE_STORAGE_CLASS>
  accessModes:
    - <KUBE_STORAGE_READ_WRITE>
  resources:
    requests:
      storage: 1Gi
  selector: 
    matchLabels: 
      type: ifw-volume      
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ifw-inbox
  labels:
    type: ifw-inbox 
spec:
  storageClassName: <KUBE_STORAGE_CLASS>
  capacity:
    storage: 1Gi
  accessModes:
    - <KUBE_STORAGE_READ_WRITE>
  persistentVolumeReclaimPolicy: Retain  
  hostPath:
    path: "<IFW_PV_INBOX>"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <IFW_PVC_INBOX>
spec:
  storageClassName: <KUBE_STORAGE_CLASS>
  accessModes:
    - <KUBE_STORAGE_READ_WRITE>
  resources:
    requests:
      storage: 1Gi
  selector: 
    matchLabels: 
      type: ifw-inbox     