apiVersion: v1
kind: PersistentVolume
metadata:
  name: ifw-volume
  labels:
    type: ifw-volume 
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  
  hostPath:
    path: "<IFW_PV_VOLUME>"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <IFW_PVC_VOLUME>
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector: 
    matchLabels: 
      type: ifw-volume
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ifw-inbox
  labels:
    type: ifw-inbox 
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany  
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: <IFW_NFS_PATH>
    server: <IFW_NFS_SERVER>
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ifw-inbox-claim
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector: 
    matchLabels: 
      type: ifw-inbox     
