apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: if-volume-claim
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000M   
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ifw-inbox-claim
  annotations:
    nfs.io/storage-path: "meta.helm.sh/release-name=nfs-subdir-external-provisioner,meta.helm.sh/release-namespace=default"
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000M   
  nfs:
    path: /var/nfs/general
    server: 10.0.0.2      