apiVersion: v1
kind: Service
metadata:
  name: {{ include "aaservices.fullname" . }}
  labels:
    {{- include "aaservices.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.ports.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: 31000
      {{- end }}
      protocol: {{ .Values.ports.protocol }}
      name: {{ .Values.ports.name }}
  selector:
    {{- include "aaservices.selectorLabels" . | nindent 4 }}
