apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aas-log-vol-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: aas-log-vol