apiVersion: v1
kind: PersistentVolume
metadata:
  name: aas-log-vol
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: <UPDATE PATH>
    type: Directory
  persistentVolumeReclaimPolicy: Retain